server:
  port: 9411
spring:
  application:
    name: cloud-sleuth-server
  sleuth:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false
